name: Python CI

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest autopep8 black

    - name: Auto-format code with black
      run: |
        black .

    - name: Autopep8 to fix PEP8 issues
      run: |
        find . -name "*.py" -exec autopep8 --in-place --aggressive --aggressive {} +

    - name: Run flake8
      run: |
        flake8 .
      continue-on-error: true

    - name: Run pytest
      run: |
        pytest --maxfail=1 --disable-warnings
      continue-on-error: false
